// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'rich-input': string;
  'richInput': string;
  'textarea': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
