// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page': string;
  'user-list': string;
  'userList': string;
}
export const cssExports: CssExports;
export default cssExports;
