// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'wrapper': string;
  'wrapper-arrowLeft': string;
  'wrapper-arrowRight': string;
  'wrapperArrowLeft': string;
  'wrapperArrowRight': string;
}
export const cssExports: CssExports;
export default cssExports;
