// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input-block': string;
  'inputBlock': string;
  'message': string;
  'message-block': string;
  'messageBlock': string;
  'room': string;
}
export const cssExports: CssExports;
export default cssExports;
